services:
  mysql:
    image: mysql:8.0
    container_name: rag-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rag
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: rag-app
    restart: always
    env_file:
      - ./env.prod
    volumes:
      - /root/llm/all-MiniLM-L6-v2:/all-MiniLM-L6-v2 
      - /root/llm/ms-marco-MiniLM-L6-v2:/ms-marco-MiniLM-L6-v2
      - ./root/my_rag:/app  
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql_data: