services:
  db:
    image: mysql:8.0
    container_name: rag-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - yxp_db_data:/var/lib/mysql 

  app:
    build: .
    container_name: rag
    environment:
      - ENV=prod          # 直接写环境变量
    volumes:
      - /root/my_rag:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  yxp_db_data:
    name: yxp_db_data 