services:
  db:
    image: mysql:8.0
    container_name: rag-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - rag_data:/var/lib/mysql 

  app:
    build: .
    container_name: rag
    restart: always
    environment:
      - ENV=prod          # 直接写环境变量
    volumes:
      - /root/llm/all-MiniLM-L6-v2:/app/models/all-MiniLM-L6-v2
      - /root/llm/ms-marco-MiniLM-L6-v2:/app/models/ms-marco-MiniLM-L6-v2
      - /root/my_rag/.venv:/app/.venv
      # 3. 映射项目代码（可选，方便改代码不用重建镜像）
      - /root/my_rag:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  rag_data: